### ISSUE TITLE
Detect RFI attacks

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#10]
Related to #5 Create some rules to detect a remote file inclusion.

**Comment by afeena** [comment]
Now we have re for detecting rfi 
`re.compile('.*(=.*(http(s){0,1}|ftp(s){0,1}):).*', re.IGNORECASE): dict(name='rfi', order=2)` 
Do we need new detection rules?

**Comment by glaslos** [comment]
No, detection is fine. Let's move on to emulation.
