### ISSUE TITLE
Make the unified system for TANNER/SNARE communication

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#100]
We can get differ types of messages from TANNER, so we should check the type and existence of some dict keys to process the page. https://github.com/mushorg/snare/blob/master/snare.py#L187

TANNER should return unified messages to make processing the result of the emulation easier. For example, now payload can be dict or str, so we should make a lot of checks to choose the action. If TANNER returns unified structured messages we will have the possibility to parse it properly. TANNER should have clear, proper api. Also we can return error messages if something goes wrong and make logs (as a option) of these errors on the SNARE side. 

Maybe we can make the types of the messages, for example: 
* Type 1 - it's a common query, no attack, nothing to do; 
* Type 2 - injectable payload (data should be shown on the current page) ; 
* Type 3 -  payload with new page; 
* Type 4 - error. 
An so on.

So, if we get the type 4, we definitely know that we need to get "error" key from the message.

It's a bit dirty description. Any advice and suggestions will be greatly appreciated

**Comment by glaslos** [comment]
Sounds good to me. We could also go similar like HTTP:
- 1 common type, but 101 is index page, 102 is css, 103 is image...
- 2 attack. 201 with inject, 202 with new page...
- 3 error. 301 req error, 302 tanner error...

etc.

**Comment by Philelis** [comment]
I think all this types should also be in the logfiles as severity. Do you agree with me?

**Comment by afeena** [comment]
@Philelis Sure, I completely agree with you, thanks :)

**Comment by afeena** [comment]
#184
