### ISSUE TITLE
Test emulators 

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#109]
Test the set of emulators with vulnerabilities scanner and find possible problems

**Comment by rnehra01** [comment]
@afeena Please explain it a bit.

**Comment by afeena** [comment]
We can use well-known [tools](https://www.owasp.org/index.php/Appendix_A:_Testing_Tools) for vulnerability search in SNARE/TANNER. It helps us understand how TANNER emulate vulnerabilities in "real" pentesting. And maybe during this testing we find some problems. Anyway, I think it will be good sometimes to test TANNER this way.

**Comment by rnehra01** [comment]
I didn't get it. I mean, do we've to test it manually against some tool such as OWASP-ZAP?

**Comment by afeena** [comment]
@rnehra01 Yes, you can use any tools you want. The main purpose - make sure that scanner detect vulnerabilities from our set of emulators (RFI, LFI, XSS, SQLi) :)

**Comment by anjali-shukla** [comment]
Did anyone try with vulnerability assessment tools to check if they show tanner as vulnerable to the emulated vulnerabilities?

**Comment by anjali-shukla** [comment]
@rnehra01 Did you try any vulnerability tool ?
I tried with OWASP ZAP but its not showing any vulnerabilities only some header content missing is being shown .I tried grabber also
