### ISSUE TITLE
Query check before any attack emulation

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#113]
If any attack is performed via `GET` request, then it should be done using one of the query params, but the code checks for attack even if there are no query param which might lead to problems such as https://github.com/mushorg/tanner/issues/111
So for emulating a `GET` request attack, there should be a check to see whether any query param is present or NOT?

**Comment by glaslos** [comment]
You are saying there are no attacks using the `GET` method without a query parameter?

**Comment by rnehra01** [comment]
As far as I know, if we don't consider `cookies`.

**Comment by glaslos** [comment]
How about DoS attacks? Can a GET request contain a body?

**Comment by glaslos** [comment]
What if an attacker accesses a file he is not supposed to access?

**Comment by afeena** [comment]
The problem in detection. If we have path like /foo=http://bar.com, it will be detected as rfi. Possible solution without checking query part - change pattern

**Comment by glaslos** [comment]
We can definitely check if there are parameters before applying a patterns that requires a parameter.

**Comment by rnehra01** [comment]
So the thing is about `LFI`, `RFI`, `SQLI`, `XSS` supported by tanner.

**Comment by rnehra01** [comment]
I think what we can do is apply a query check for the attacks I mentioned. Hopefully in future when tanner supports DoS, we won't do query check for that.

**Comment by rnehra01** [comment]
Instead of a simple query check, I've thought of a way which will make the code nicer to read.
Currently, we're checking for attack in the whole URL like `.*=((\.\.|\/).*)` for `LFI`.
Now we can extract all the URL query param in a `dict` and pass it to the emulator, which will check for each query parameter, this way we can get rid of extra `.*=` and will just check exact attack. It'll definitely make the code nicer and will resolve the issue.
What's say? @afeena @glaslos

**Comment by afeena** [comment]
@rnehra01  You suggest to check the attack type by each emulator? I think we should detect attack type before running specific emulator. 

You can try to implement it and we will discuss the result :)

**Comment by rnehra01** [comment]
Yeah, I mean that before running emulators, my bad. I'll implement soon.
