### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#117]
**Upd:**

- Write docs about config
- <del>Update session docs (cookie)</del>

**Comment by rnehra01** [comment]
@afeena Are you talking about https://github.com/mushorg/tanner/blob/master/tanner/config.py ?
By the way, what does this file https://github.com/mushorg/tanner/blob/master/docs/source/conf.py for ?

**Comment by afeena** [comment]
@rnehra01 `conf.py` - it's a config for [sphinx docs](http://www.sphinx-doc.org/en/stable/config.html). Yes, I'm talking about our config. In docs we should describe values which can be set in config file and mention the possibility to set only separate sections which you want to change and so on.

**Comment by rnehra01** [comment]
@afeena done the first one too.
