### ISSUE TITLE
LFI false positive

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#121]
If we pass URLs like `?file=/etc/pas`, emulator still shows a similar result to `?file=/etc/passwd`

**Comment by afeena** [comment]
In the past we check LFI_ATTACK pattern, not LFI_FILEPATH - maybe this is the problem now?

**Comment by rnehra01** [comment]
I think issue is due to this `https://github.com/mushorg/tanner/blob/master/tanner/emulators/lfi.py#L20`.

**Comment by afeena** [comment]
You are right :)
