### ISSUE TITLE
Where can I change the logging?

### ISSUE THREAD

**Issue by Philelis** [mushorg/tanner#123]
Hey,
I need a valid json format another application. I turned local logging on and saw:

> {'method': 'GET', 'peer': {'ip': '192.168.122.1', 'port': 58280}, 'path': '/images/foo.jpg', 'response_msg': b'{"response": {"message": {"detection": {"order": 1, "name": "index"}, "sess_uuid": "xxx"}}, "version": 1}', 'uuid': 'xxx, 'status': 200, 'headers': {'cache-control': 'max-age=0', 'host': '192.168.122.177', 'user-agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'accept-encoding': 'gzip, deflate', 'referer': 'http://192.168.122.177/', 'accept': '*/*', 'connection': 'keep-alive', 'cookie': 'sess_uuid=xxx', 'accept-language': 'en-GB,en;q=0.5'}, 'cookies': {'sess_uuid': 'xxx'}}

I don't want to have this b after response_msg and I need to change the output to:

> {"method": "GET","peer": {"ip": "192.168.122.1","port": 58280},"path": "/images/foo.jpg","response_msg": {"response ": {"message ": {"detection ": {"order ": 1,"name ": "index"},"sess_uuid ": "xxx"}},"version ": 1},"uuid": "xxx","status": 200,"headers": {"cache-control": "max-age=0","host": "192.168.122.177","user-agent": "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0","accept-encoding": "gzip, deflate","referer": "http://192.168.122.177/","accept": "*/*","connection": "keep-alive","cookie": "sess_uuid=xxx","accept-language": "en-GB,en;q=0.5"},"cookies": {"sess_uuid": "xxx"}}

I did not found something like b', only in the test files. I search for that in snare and tanner.
Please help me. :)

**Comment by afeena** [comment]
Hello @Philelis, the problem is here  https://github.com/mushorg/tanner/blob/master/tanner/server.py#L62
`_make_response` function return byte object.

Do you need help in fixing?

**Comment by Philelis** [comment]
Yeah that would be great, how can I change this?

**Comment by afeena** [comment]
You can replace L62 with `session_data['response_msg'] = response_msg.decode('utf-8')`

**Comment by afeena** [comment]
Do you have problems with validation of the whole `tanner_report` file? I have. Maybe we should pay attention on this problem. Let me know if you have the same problem. 
Thank you very much for the issue :)

**Comment by Philelis** [comment]
Do you mean the tanner log or the local log? On local with your fix there is no b, on tanner log there is it. Do you also have this f... problem with` 'response_msg': '{some correct things}}}' `? I think this a problem contained with the array (every entry between '' or I am false?), but I don't know exactly.

Have you an idea where to change the ' to " ? Another thing for json :D, otherwise it is possible to change both issues after creating the logs.

**Comment by afeena** [comment]
I meant local log. When I tried to validate it - I had errors.

Yeah, I want to make local log file completely valid json. Replace `'` with `"` and so on.

**Comment by Philelis** [comment]
Yeah I see my two problems. One is the `'` the other one is after `response_msg:` and at the and of the`{ `after `response_msg`. (Often ends with version and number or `}}}`)

**Comment by afeena** [comment]
@Philelis It will be great if you take a look at the pr #124 and give me feedback

**Comment by Philelis** [comment]
:/ 
Tested it with snare and now snare shows me that error when I try to use it with tanner:
```
Request path: /
Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8
Expecting value: line 1 column 1 (char 0) {'method': 'GET', 'status': 200, 'cookies': {'sess_uuid': 'xxx'}, 'uuid': 'xxx', 'path': '/', 'peer': {'port': 36606, 'ip': '192.168.122.1'}, 'headers': {'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'Connection': 'keep-alive', 'Cookie': 'sess_uuid=xxx', 'Upgrade-Insecure-Requests': '1', 'Host': '192.168.122.177', 'Cache-Control': 'max-age=0', 'Accept-Language': 'en-GB,en;q=0.5', 'User-Agent': 'Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:52.0) Gecko/20100101 Firefox/52.0', 'Accept-Encoding': 'gzip, deflate'}}
Error handling request
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 275, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 191, in handle_request
    if 'payload' in event_result['response']['message']['detection']:
TypeError: 'NoneType' object is not subscriptable
Task exception was never retrieved
future: <Task finished coro=<ServerHttpProtocol.start() done, defined at /usr/lib64/python3.5/site-packages/aiohttp/server.py:225> exception=TypeError("'NoneType' object is not iterable",)>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 275, in start
    yield from self.handle_request(message, payload)
  File "snare.py", line 191, in handle_request
    if 'payload' in event_result['response']['message']['detection']:
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/lib64/python3.5/site-packages/aiohttp/server.py", line 325, in start
    yield from self.handle_error(500, message, None, exc)
TypeError: 'NoneType' object is not iterable
```

**Comment by afeena** [comment]
It's strange, because I don't have this error. Did you make any local changes?

**Comment by Philelis** [comment]
I know where the error is!
If the log is empty I got some error, otherwise it works. Now I will have a look on your outputs ;)

**Comment by Philelis** [comment]
They look really good. The first one should begin with `[`. If your log is empty it don't work, but if you have only `[` in this file it will work. Tomorrow I will test it again.

**Comment by afeena** [comment]
Sorry, I didn't mention that I deleted old logs and started with new one. 
When you don't have a file, TANNER create initial file with `[]` object, on the next step, last char will be deleted and new json part will be added with `]` at the end.
If you will have any problems - just let me know ;)

**Comment by Philelis** [comment]
Hey,
I tried it again. If you save it on existing data no problem, also on a new file no problem. Only if you already have an empty file you got my error :D
Good fix thanks :)
If you want to use it with Elastic you should change `out.write(",") ` to `out.write("\n") `, but your solution is full json valid 👍

**Comment by Philelis** [comment]
@afeena I don't want to have this `[` at the beginning is there any possible to write direct into the file without an 500er error? I tried to delete `json.dump([], out)` or to change the line above.

**Comment by Philelis** [comment]
Found it, I only have to check it now in the app :). The logs show me the output that I want to see.
