### ISSUE TITLE
Missing tests

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#129]
Test are missing for `SQLI`, `XSS` and `LFI` in for `server.py`.

**Comment by rnehra01** [comment]
@afeena Assign me this issue.

**Comment by afeena** [comment]
Maybe it's a good idea to make tests for base emulator? And test the detection and payload there? Now we don't have any tests for base emulator.

**Comment by rnehra01** [comment]
Yeah, that sounds better.
