### ISSUE TITLE
Change page(location) for payload injection

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#141]
Currently, each payload is injected on the `index.html` page but that doesn't happen in real scenario always. So payload should be injected into the appropriate (page)location.

**Comment by rnehra01** [comment]
@afeena We can use this `https://github.com/mushorg/tanner/blob/master/tanner/emulators/xss.py#L33`, I guess for all other emulators. Just wondering, why didn't it was used earlier?

**Comment by afeena** [comment]
@rnehra01 Yes, I think we can :)

**Comment by rnehra01** [comment]
#155
