### ISSUE TITLE
Improve base emulator architecure

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#148]
The current base emulator has become messy due a bunch of different emulators with different ways of working. Here I'm proposing a solution to handle different emulators in a standard way.
Each emulator will have a `scan` method that detects the presence of the corresponding attack in `param value` passed to it.
In the base emulator, this scan method will be called for each emulator for each `GET` and `POST` parameter.
##### BASE HANDLER
```
for each get_param:
    for each emulator:
       if (emulator.scan(param)) detection = {emulator_type, order}
//Get payload from corresponding emulator

//Similarly for post parm
```
E.g.
###### LFI
```
def scan(param):
    if (re.match(LFI.pattern, param)) return true
    else return false
```
Similary for other emulators.
In this way, we'll have a standard way in which new emulator will be formed and there won't be any need to do much change in the base emulator when new emulator will be added.
This is a basic idea. There might be some minor changes if required.

**Comment by afeena** [comment]
I like the idea :) Go for it :)

**Comment by glaslos** [comment]
Do you think there will be scenarios where an emulator requires multiple parameters at the same time to do a detection?

**Comment by rnehra01** [comment]
I've seen some scenarios where we need to make an attack using multiple parameters a the same time due to certain checks. But in these emulators, there are no checks so simply any injection can be done using one parameter.

**Comment by rnehra01** [comment]
#149
