### ISSUE TITLE
Docker affects other containers

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#160]
When I have some containers running and then run cmd injection, tanner removes my containers and I have only attacker container in the list. 

**Upd**: It might be on the delete step. I created container and ran cmd injection, but containers was in the list. but after some time, all container were disappeared.

**Comment by rnehra01** [comment]
@afeena Are you saying that some `containers` that you run manually, tanner removes them too? Because as far as I know, Tanner removes only those containers which are related to expired sessions.

**Comment by afeena** [comment]
@rnehra01 Yes, I manually started container, ran the tanner and made cmd execution. Then I ran `docker ps` and didn't find my container. I made about 5 tests and got the same result.

**Comment by afeena** [comment]
I don't know the _real_ reason why containers were deleted, but I think we should find this reason.

**Comment by rnehra01** [comment]
Could you try 'docker ps -a -q' ?

On 24 Jun 2017 5:47 p.m., "Evgeniya" <notifications@github.com> wrote:

I don't know the *real* reason why containers were deleted, but I think we
should find this reason.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/mushorg/tanner/issues/160#issuecomment-310835209>, or mute
the thread

**Comment by afeena** [comment]
I don't see the big difference between `docker ps -a` and `docker ps -a -q` :)

**Comment by rnehra01** [comment]
@afeena I'm unable to reproduce this.
This is how I tried:
First, start a new container using `docker run -it busybox`
Start Tanner and Snare, browse `localhost:8080/?a=ls`
After that, I run `docker ps -a` and found two containers
After that I waited till `KEEP_ALIVE_TIME` seconds, and browse `localhost:8080/?a=ls`
Then run `docker ps -a`, again found two containers.

**Comment by afeena** [comment]
http://i.imgur.com/KCO0CEP.png

**Comment by afeena** [comment]
Just print deleted containers in tanner.
I think it's a good proof of this bug. But I don't have clear algorithm to reproduce it.
<img width="871" alt="conemu64_2017-06-26_16-34-53" src="https://user-images.githubusercontent.com/8390928/27537654-3778444e-5a8e-11e7-8525-600ad0584d98.png">
<img width="370" alt="conemu64_2017-06-26_16-35-09" src="https://user-images.githubusercontent.com/8390928/27537653-37744f60-5a8e-11e7-995c-db2e3c6f3e87.png">

**Comment by afeena** [comment]
The problem in https://github.com/mushorg/tanner/blob/master/tanner/session.py#L77
We don't check `self.associated_env`. It can be `None` so when we try to list containers with filter `name=None` we get unexpected behavior. Solution - check the variable for None :)

Btw, maybe it is better to use [`get` ](https://docker-py.readthedocs.io/en/stable/containers.html#docker.models.containers.ContainerCollection.get)function for containers getting  instead of list?

**Comment by rnehra01** [comment]
I initially tried with `get` but the thing is, it raises an Exception if the container is NOT found, so it looks weird to do a task based on Exception.
I think we should fix it by checking `None`.

**Comment by glaslos** [comment]
Generally a lot of things in Python are based on raising and catching exceptions, so I would see it as valid solution.
