### ISSUE TITLE
Add new features to tanner api

### ISSUE THREAD

**Issue by rnehra01** [mushorg/tanner#163]
Proposed features:
1. Get all sessions related to a `snare-uuid`
2. Get a session info from its `sess-uuid`
3. Get all the sessions from a given
   - `IP`
   - `owner-type`
   - `attack-type`
   - `user-agent`

Other ideas are welcomed.

**Comment by afeena** [comment]
I'd also suggest you to add the possibility to get sessions by time periods.
And maybe combined statistics by snare uuid: number of sessions, number of attacks, average session time, most frequent attack type etc

**Comment by rnehra01** [comment]
I didn't understand the combined statistics thing, could you explain it a bit?

**Comment by afeena** [comment]
I meant that we could get statistics by groups. e.g. one snare uuid can have lots of separate sessions, so we can calculate such values as:
- get number of sessions
- get average duration of the all sessions
- get sessions with attacks
- get most frequent attack
etc.

**Comment by rnehra01** [comment]
#166
