### ISSUE TITLE
Cleanup docker containers on shutdown

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#164]
If we stop tanner before deleting old containers, we should delete them on the shutdown stage, in other case, we get something like this:

![image](https://user-images.githubusercontent.com/8390928/27623013-d523aac4-5bf3-11e7-9857-f455d2014495.png)

**Comment by rnehra01** [comment]
Apart from containers, we also have DBs. So I'm thinking of deleting all sessions before the shutdown, which will delete containers and DBs.

**Comment by rnehra01** [comment]
@afeena Anything you want to say about my fix?

**Comment by afeena** [comment]
I completely agree that we should delete DBs too :)
