### ISSUE TITLE
Tanner api auth

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#170]
Tanner api is completely open, so, if someone knows the address of the tanner server, he or she can get the list of all snare's uuids and info about all sessions. 

It might be suitable to add api keys: 
1) Client key for people who use someone's tanner server (e.g. based on snare uuid which is known for client)
2) Admin key which gives full access to info

**Comment by glaslos** [comment]
For now I would make it accessible from localhost only.

**Comment by afeena** [comment]
@glaslos We have a discussion with @viskey98 about this task and I would like to ask your opinion - should we try to implement it later somehow?

**Comment by glaslos** [comment]
How about generating a token when you start Tanner that you can use for authentication with the API. The token will be shown on the terminal. We could also look into OAuth using Google, Twitter or GitHub?

**Comment by afeena** [comment]
#268
