### ISSUE TITLE
Web request freezing

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#179]
When I tried to get sessions, tanner web freezing. I've found that it might be because of the large number of sessions in snare_uuid (42297 in list). When we make request to redis, it takes range from 0 to -1 (end) https://github.com/mushorg/tanner/blob/develop/tanner/api/api.py#L43  I set the count as 10 and everything works well.
I suggest to request less sessions per request.

**Comment by rnehra01** [comment]
@afeena Could you verify the same issue happens in the case of API too.

**Comment by afeena** [comment]
You can use our develop server for testing :)

**Comment by afeena** [comment]
#181
