### ISSUE TITLE
Example of the INI config file

### ISSUE THREAD

**Issue by standa4** [mushorg/tanner#187]
Hello,

I would like to ask for the example of the ini config file. More specifically I would like to know how to write the "emulator_enabled:" values in the section EMULATORS. I do not know how to rewrite it from the json.

Thank you.

Stanislav

**Comment by afeena** [comment]
Hi Stanislav, thanks for the issue. 
I think we should fix it in tanner. You are right, it's hard to rewrite this section from json. I hope we will fix it soon.
