### ISSUE TITLE
Storing events

### ISSUE THREAD

**Issue by dufferzafar** [mushorg/tanner#2]
Currently, Tanner just responds to events by detecting some known patterns, and responding with payloads (if they exist.)

Do we also plan to store these events (in some database perhaps) for analysis later?

I'm also just guessing that this will be done on Tanner's side, rather than Snare's. 

I'd be interested in working on this feature (if it is needed, of course,)

P.S: It'd be nice if you could maybe just add some issues about functionalities that you feel makes sense in Snare/Tanner.

**Comment by glaslos** [comment]
Definitely needed and you are right, there is no reason to do this in snare and tanner is where everything comes together.
I was looking into time series databases, influxdb is something I have used before and looks very promising. If we want to focus on search, we probably want to go for something that is better for full text indexing (e.g. ElasticSearch). Maybe we use both? influxdb for counters and statistics and ES for the full data and search?
There will be also a web interface on top of tanner where you can look up your sensors UUID (part of every request to tanner) to get statistics.

**Comment by glaslos** [comment]
Thinking about it, a simple counter database to display the activities from a sensor might be a good starting point and basis for the UI #3 
Have also a look at RethinkDB, they are pretty cool as they have a pub/sub feature that let's you build graphs that update as data comes in using web sockets.

**Comment by glaslos** [comment]
See #68
