### ISSUE TITLE
Return tanner version by request

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#200]
For new tanner-snare communication it's needed to check tanner version on the snare side.
So tanner should return version by request. e.g. `/version'

**Comment by rnehra01** [comment]
Currently, Tanner sends `version` in `detection` field. So once we'll implement get `version` by requests `/version` I think we can remove `version` from `detection` field as it doesn't fit well there. Maybe we can make a new field named `version` here `https://github.com/mushorg/tanner/blob/master/tanner/server.py#L58`

**Comment by glaslos** [comment]
Closed with #217
