### ISSUE TITLE
Move documentation to readthedocs.org 

### ISSUE THREAD

**Issue by nsmfoo** [mushorg/tanner#204]
To make the extra documentation that is available more easily accessible. I suggest a move to readthedocs.org

**Comment by viskey98** [comment]
I would like to work on this issue, but can anyone tell me how to start with? I haven't had any experience with readthedocs.org

**Comment by glaslos** [comment]
I recommend starting with creating a test documentation and then adapt Tanners documentation.

**Comment by glaslos** [comment]
It might need some cleaning, but it seems to work: http://tanner.readthedocs.io/en/latest/
