### ISSUE TITLE
Travis Error in ftp_download

### ISSUE THREAD

**Issue by viskey98** [mushorg/tanner#234]
In the latest PRs travis is failing in test for ftp_download.
`test_ftp_download (tanner.tests.test_rfi_emulation.TestRfiEmulator) ... FAIL`
I tried to simulate this test in my machine and test_ftp_download worked properly. So this error should be caused in travis's side. I think travis is unable to connect to the ftp server.

**Comment by afeena** [comment]
The better solution for this is to isolate our functionality ftp lib functionality, so we need to mock ftp functionality

**Comment by viskey98** [comment]
Please explain a bit, how to mock? So that I can do it on my own

**Comment by afeena** [comment]
@viskey98 look at this https://docs.python.org/3/library/unittest.mock-examples.htm
If you have any problems, I will be glad to help :)

**Comment by viskey98** [comment]
Fixed by #236
