### ISSUE TITLE
Logging exceptions better

### ISSUE THREAD

**Issue by xandfury** [mushorg/tanner#238]
Instead of using `logging.error` use `logging.exception`. [`logger.exception`](http://docs.python.org/library/logging.html#logging.Logger.exception) will output a stack trace alongside the error message. With `logging.error` only the formatted error message would display and the traceback would be thrown away.

More info: https://stackoverflow.com/questions/5191830/how-do-i-log-a-python-error-with-debug-information?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by xandfury** [comment]
I also couldn't get my head around ***not*** using module level logging such as [here](https://github.com/mushorg/tanner/blob/d55cdda1a6d60f39e3f0d027b1efda2582706a22/tanner/utils/docker_helper.py#L10). Is there a specific reason for doing so?

**Comment by afeena** [comment]
@xandfury Good point with logging exception :) Would you like to implement it? :)

**Comment by xandfury** [comment]
Yeah sure :-) I have been working on a PR; Will send to you for reviewing soon.

**Comment by xandfury** [comment]
@CyberDrudge please go ahead. I couldn't find time after making some trivial changes.
