### ISSUE TITLE
not able to run tanner web

### ISSUE THREAD

**Issue by anjali-shukla** [mushorg/tanner#241]
I have installed docker and everything needed for tanner. Tanner and Tannerapi is running but tannerweb is giving error. The screenshot of error is attached below.
![tannerweb](https://user-images.githubusercontent.com/35517694/38164448-a89ec0ac-3522-11e8-8b7f-a8b31f870925.png)

**Comment by viskey98** [comment]
@anjali-shukla Have you installed the requirements using `pip3 install -r requirements.txt` ? Because if you have a different version of aiohttp installed it might cause some trouble.

**Comment by afeena** [comment]
@anjali-shukla Thanks for the issue. It was a problem with dependency. Now should be fixed by #243 - please, check it :)

**Comment by anjali-shukla** [comment]
yeah , it worked fine. Thank you
