### ISSUE TITLE
How to test if emulators are working?

### ISSUE THREAD

**Issue by anjali-shukla** [mushorg/tanner#245]
Can anyone help me  check if emulators are working fine??
How to know that they are configured properly??
how to see the dummy database created??
Do i have to edit the config file for mysql database ??

**Comment by anjali-shukla** [comment]
I want to know the input test sequence for each vulnerability to check if the tanner responds properly.

**Comment by mzfr** [comment]
hey @anjali-shukla have you gone through the [Tanner docs](http://tanner.readthedocs.io/en/latest/). They have some info about the emulation too.

**Comment by anjali-shukla** [comment]
yeah , i went through them. But i have no idea what to give input to test for each attacks?
How to check if database is being created ?

**Comment by anjali-shukla** [comment]
tanner is not creating the database.
Any help??
![db_error](https://user-images.githubusercontent.com/35517694/38242389-50e17594-3752-11e8-955a-d5fad95f043a.png)

**Comment by afeena** [comment]
@anjali-shukla Have you changed your config according to your database credentials?

**Comment by anjali-shukla** [comment]
I just have to change the password right ??
user is root only. and after that i will have to run 
sudo python3 setup.py install

**Comment by anjali-shukla** [comment]
In sql injection , for every query its giving the mysql syntax error only.
how to see some table of the database??

**Comment by anjali-shukla** [comment]
can we see particular table from the database in sql injection??
Like if i give SELECT * FROM users; , it should show the users column right?
I checked the tanner_db database and when i give this command it shows the user tables
But when i give this query from snare it just shows the default you have error in your mysql syntax .

**Comment by afeena** [comment]
@anjali-shukla have you used sqlite or mysql module?

**Comment by anjali-shukla** [comment]
mysql

**Comment by afeena** [comment]
@anjali-shukla Could you please provide exact command, which you used for testing sqli?

**Comment by anjali-shukla** [comment]
1\'UNION SELECT 1,2,3,4
'1\'UNION SELECT 1,2,3,4:'
UNION SELECT 1,2,3,4
'UNION SELECT 1,2,3,4;'
'SELECT * from users WHERE id=1 UNION SELECT 1,2,3,4;'
SELECT * from users WHERE id=1 UNION SELECT 1,2,3,4

**Comment by anjali-shukla** [comment]
1\'UNION SELECT 1,2,3,4
'1\'UNION SELECT 1,2,3,4;'

**Comment by rnehra01** [comment]
@anjali-shukla I tested `http://localhost:8080/?id=1'UNION SELECT 1,2,3,4` and it gave me `[1, 2, 3, 3] [1, 'solange7815', 'cherryl9499@live.com', 'VbB&-1;)']`

**Comment by anjali-shukla** [comment]
how to drop a column of table like what should the query be like to drop table with id=1?

**Comment by anjali-shukla** [comment]
@ rnehra01 can you tell me how to test for rfi emulator??
What should I give as query?

**Comment by afeena** [comment]
@anjali-shukla you can get some information about rfi here https://www.owasp.org/index.php/Testing_for_Remote_File_Inclusion

lfi:
https://www.owasp.org/index.php/Testing_for_Local_File_Inclusion
