### ISSUE TITLE
No correlation between log and downloaded file

### ISSUE THREAD

**Issue by t3chn0m4g3** [mushorg/tanner#261]
The other day I have been noticing that there does not seem to be a correlation between downloaded files (i.e. wrt to a RFI) and the corresponding log entry. There should be an addition to the log regarding the written file alongside with a hash.

**Comment by afeena** [comment]
Thanks for the issue :) I agree with you, now we log only errors in rfi, so it should be changed :)

**Comment by t3chn0m4g3** [comment]
Any progress on this?

**Comment by t3chn0m4g3** [comment]
Can someone please have a look 😃 T-Pot 18.10 will have SNARE / TANNER as default web honeypot and it would be awesome if there was a solution for that 👼

**Comment by t3chn0m4g3** [comment]
Awesome! Thank you!
