### ISSUE TITLE
RFI and code injection emulator issue with mimetype on Ubuntu 18.04

### ISSUE THREAD

**Issue by Gerard42** [mushorg/tanner#274]
When installing TANNER on Ubuntu 18.04 I got the following error when testing the RFI and code injection emulators:

`ERROR:tanner.php_code_injecton:get_injection_result: Error during connection to php sandbox 0, message='Attempt to decode JSON with unexpected mimetype: application/octet-stream'`

Probably the issue described by: https://stackoverflow.com/questions/48840378/python-attempt-to-decode-json-with-unexpected-mimetype

I solved it for my instance by using` rfi_result = await resp.text()` in rfi.py and php_code_injection.py instead of `resp.json()` and returning with return `json.loads(rfi_result)`. Should probably be properly fixed by changing phpox?

PS: When installing on Ubuntu 18.04 I had to start phpox with sudo python3 sandbox.py --phpbin php due to PHP version 7.2 instead of 7.0, might be good to add to the docs.

**Comment by afeena** [comment]
Hi @Gerard42 Thanks for the issue and suggested solution! I will look into the problem in a couple of days :)

**Comment by afeena** [comment]
Changes have been done on tanner and phpox side and now on master.
