### ISSUE TITLE
No config file found

### ISSUE THREAD

**Issue by XMUsuny** [mushorg/tanner#275]
Docker works well, but everytime I start tanner, there are some error in /opt/tanner/tanner.log:

docker.auth.find_config_file: Trying paths:['/home/admin/.docker/config.json', '/home/admin/.dockercfg']
docker.auth.find_config_file: No config file found

I can't find .docker or .dockercfg in /home/admin. And when I use sqlmap to scan the snare server, tanner.log isn't updated. So how I fix it?

**Comment by afeena** [comment]
Hi @XMUsuny Actually, it's not an error, it's debugging message  (https://github.com/docker/compose/issues/3767). 

Could you please describe the problem with sqlmap a bit more?

**Comment by afeena** [comment]
In case of any new problems, please create new issue
