### ISSUE TITLE
Trouble Installing Tanner

### ISSUE THREAD

**Issue by monsterhunterboy98** [mushorg/tanner#287]
My apologies for the trouble caused, I could not find any videos regarding the installation steps for tanner but I pretty much followed the steps stated in github. May I know what steps i missed or wad went wrong?

Redis Server:
![image](https://user-images.githubusercontent.com/45062471/50626493-98242880-0f69-11e9-88ab-fc99982ac7b3.png)

Tanner:
![image](https://user-images.githubusercontent.com/45062471/50626517-affbac80-0f69-11e9-8d07-7ded3e88e223.png)
![image](https://user-images.githubusercontent.com/45062471/50626557-e0434b00-0f69-11e9-99b9-098973147709.png)
![image](https://user-images.githubusercontent.com/45062471/50626570-ee916700-0f69-11e9-9509-4c77a90e56dd.png)

**Comment by monsterhunterboy98** [comment]
Sorry the error message was too long

**Comment by monsterhunterboy98** [comment]
****

**Comment by monsterhunterboy98** [comment]
Im pretty sure redis is up:
![image](https://user-images.githubusercontent.com/45062471/50630000-ee996300-0f79-11e9-8f1a-42e8da5c3591.png)

**Comment by afeena** [comment]
@monsterhunterboy98 have you run docker as well?

**Comment by glaslos** [comment]
@monsterhunterboy98 please don't use screenshots but post the actual text of the exception.

**Comment by afeena** [comment]
@monsterhunterboy98 Doest the problem still exist?
