### ISSUE TITLE
There are very less emulators. We should cover more attacks. 

### ISSUE THREAD

**Issue by amanjiofficial** [mushorg/tanner#293]

**Comment by rnehra01** [comment]
During this summer, we are expecting to increase that number. I have also added some suggestions in the project goals https://gsoc.honeynet.org/#art-prop-17

**Comment by amanjiofficial** [comment]
I would like to work on padding oracle vulnerability.

**Comment by Parth1811** [comment]
@amanjiofficial, can you please describe in more detail how can accomplish this. Can you link any resource from where I could read more about this it would be quite helpful?
I would like to know more about this and whether or not its already implemented as this is a year old ticket.

**Comment by glaslos** [comment]
Closing this issue as there is no concrete problem description.
