### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#3]
Input should be a sensor UUID (part of every request to tanner). Something like `/api/<uuid>/stats`
Should show some basic stats regarding the activity from the sensor.

**Comment by afeena** [comment]
1) What should we do if we have lots of info? E.g., we have 1,000,000 records for certain SNARE uuid, how we should return its info? We can split it into pages::
``/api/stats?uuid=<uuid>&c=100&p=1`` . 
So, do we need any navigation tools on the page? Or we should not return all the sessions info? Maybe we should return only summary statistics, e.g.:

- sessions count
- attacker's sessions
- last activity timestamp
- number of certain attack types
- smth else

2) Do we need more functions? e.g. return all the sessions with possible owner 'attacker' or any other selections.

**Comment by glaslos** [comment]
I'd keep it simple for now. Show the last x sessions (50?), and maybe a timeline with events/time.

**Comment by afeena** [comment]
Basic UI features was implemented in #173. If we need some new features - It's better to open new issue.
