### ISSUE TITLE
No error message for SQLite

### ISSUE THREAD

**Issue by gaochua** [mushorg/tanner#312]
`sqli` emulator supports both MySQL and SQLite, but returned error only supports MySQL: https://github.com/mushorg/tanner/blob/master/tanner/emulators/sqli.py#L45

**Comment by rnehra01** [comment]
It needs fixing.

**Comment by rjt-gupta** [comment]
@rnehra01 For SQLite error should be - `ERROR NEAR line x: near "": syntax error` right?

**Comment by rnehra01** [comment]
I don't remember, I guess you can install SQLite and check it.

**Comment by rjt-gupta** [comment]
We can close this issue.
