### ISSUE TITLE
Store files downloaded by RFI emulator.

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#33]
Store the file with the file name being a md5 hash of the file.
Think about if we want to pass the path to the file or the file content to PHPOX.

**Comment by afeena** [comment]
In which folder should we store downloaded file?

**Comment by glaslos** [comment]
`/opt/tanner/files` should be fine.

**Comment by afeena** [comment]
I used for the first time /opt/tanner/, but it didn't pass the tests :(
https://travis-ci.org/afeena/tanner/builds/137102392

**Comment by glaslos** [comment]
I assume you have to use a temporary folder for tests. I assume they don't run the tests as root or protect that folder.

**Comment by afeena** [comment]
Can we close this issue with   4b613af ?
