### ISSUE TITLE
Misleading Installation guide in README.md

### ISSUE THREAD

**Issue by Parth1811** [mushorg/tanner#354]
The [getting started](https://github.com/mushorg/tanner#getting-started) section in the README is a bit confusing for newcomers, I think.

It should be clearly mentioned that `redis` and `php sandbox` both are compulsory for tanner to function while docker may be an optional alternative if someone is unable to set up the environment on their machine.

Also, for me, Python3.5.2 was causing some problems with the dependencies especially `aiohttp` whose lastest version requires python3.6.x and above.

**Comment by afeena** [comment]
@Parth1811 thanks for reporting :)
python3.5 is indeed outdated, so feel free to make changes :)
