### ISSUE TITLE
Replace ftp with aioftp

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#365]
In order to make code consistently async, it's better to move to aioftp for RFI
https://github.com/aio-libs/aioftp

**Comment by steve7158** [comment]
@afeena can you please tell me how to run the rfi emulator. I made the required changes in PR #385 and tested the code separately but i am not sure how it will work with the tanner. :)

**Comment by afeena** [comment]
https://github.com/mushorg/tanner/pull/398
