### ISSUE TITLE
Permissions error

### ISSUE THREAD

**Issue by GSMcNamara** [mushorg/tanner#394]
This:

LOGGER: 
  log_debug: /tmp/tanner/tanner.log
  log_err: /tmp/tanner/tanner.err
 
in https://github.com/mushorg/tanner/blob/master/docker/tanner/dist/config.yaml causes a permission issue when trying to boot the Docker container. I changed the values to the following as a test and they seem to work:

LOGGER: 
  log_debug: /var/log/tanner.log
  log_err: /var/log/tanner.err

However perhaps this location isn't ideal.

**Comment by t3chn0m4g3** [comment]
It's designed to be started with the `docker-compose.yml` you can find [here](https://github.com/mushorg/tanner/blob/master/docker/docker-compose.yml) which creates the necessary permissions.
