### ISSUE TITLE
LFI emulation

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#4]
Right now the [LFI](https://en.wikipedia.org/wiki/File_inclusion_vulnerability) emulation is very [limited](https://github.com/mushorg/tanner/blob/932249c0b67ce7aeb3a4e7b9118ce428fdf303ef/data/passwd) we probably want to add a virtual file system similar to what [we have](https://github.com/mushorg/glastopf/tree/66d0d42aa10c4c68e38dfb9301dc45871719b596/glastopf/modules/handlers/emulators/data/virtualdocs/linux) for Glastopf while considering issue #1

**Comment by afeena** [comment]
Do we need to run TANNER into UML, or our application should communicate with UML by another way?
