### ISSUE TITLE
tannerweb issue

### ISSUE THREAD

**Issue by Haotian-Shi-cyber** [mushorg/tanner#403]
im trying to run tannerweb but got following issues
![image](https://user-images.githubusercontent.com/62081228/106400683-cd84f400-6417-11eb-96fa-d7f2d93d9016.png)

**Comment by mzfr** [comment]
@Haotian-Shi-cyber Please check the directory from which you are running the command.

It might work if you run this command inside the `tanner/` directory.

**Comment by Haotian-Shi-cyber** [comment]
@mzfr you are right, thx

**Comment by Haotian-Shi-cyber** [comment]
![image](https://user-images.githubusercontent.com/62081228/106440399-baead900-6470-11eb-93a8-cd0294a05363.png)
its running but cannot be accessed? what does the web look like

**Comment by mzfr** [comment]
@Haotian-Shi-cyber Read the documentation and see if you can access any endpoint,
