### ISSUE TITLE
User, tool, crawler and attacker

### ISSUE THREAD

**Issue by Nicocimbali** [mushorg/tanner#407]
Hi,
I saw in the logs that tanner makes a division of users which can be: user, tool, crawler and attacker, I wanted to know based on what tanner does this classification? And what is the difference between these categories?

**Comment by mzfr** [comment]
Hey @Nicocimbali 

You can see the code for `choosing profile`, [here](https://github.com/mushorg/tanner/blob/master/tanner/sessions/session_analyzer.py#L115).

To detect __crawler__ this([session_analyzer#L151](https://github.com/mushorg/tanner/blob/master/tanner/sessions/session_analyzer.py#L151)) function is used.

For detecting __attacker__, this([session_analyzer#L172-L188](https://github.com/mushorg/tanner/blob/master/tanner/sessions/session_analyzer.py#L172-L188)) function is used.
