### ISSUE TITLE
GSoC'22 - HTTP requests evaluation

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#419]
**Mentors**: Evgeniia Tokarchuk @afeena, Mehtab Zafar @mzfr 

**Project type:** Improving existing tool

**Project hours:** 350

**Skill required:**
– Python 3
– Experience in Machine Learning (any)
– Optional: experience with (and/or) pytorch/scikit-learn/xgboost/other ML lib

**Description**:
TANNER is a remote data analysis and classification service to evaluate HTTP requests. However, the evaluation and classification are built upon handcrafted heuristics. That leads to the adaptation and generalization problem while classifying for attacks. With the advances of machine learning algorithms nowadays and the availability of various datasets, it is potentially promising to build a more reliable classification system. Moreover, after years of running TANNER, there are multiple available TANNER logs, which can be used for training.

This project will include several steps:
– Analyzing current error rates for classifications (setting the baseline)
– Data preparation/cleaning
– Designing and implementing the prototype of the ML-based classification system
– Incorporating a new system into the TANNER (only in case of successful outcome)

**Comment by mohamedmostafadawood** [comment]
When can I discuss the proposal?
