### ISSUE TITLE
TypeError: zrevrangebyscore() got an unexpected keyword argument 'offset' when running through docker

### ISSUE THREAD

**Issue by JohnBonJo** [mushorg/tanner#425]
on line 42 [tanner/tanner/api/api.py](https://github.com/mushorg/tanner/blob/a98b7ab6f32a14f8301bdafc6c8fc9ecc1806e28/tanner/api/api.py#L42)

![offset_error](https://user-images.githubusercontent.com/74373209/177613683-f0b777b8-c61b-4995-811c-7fff9a703f71.png)

same as this issue [https://github.com/mushorg/tanner/issues/416](https://github.com/mushorg/tanner/issues/416)

On that issue [afeena](https://github.com/afeena) suggested to use the develop branch. 
I've tried it and got other errors.

**Comment by toyray** [comment]
Changing that line to `query_res = await self.redis_client.zrevrangebyscore(uuid, 0, -1, start=0, num=count)` seems to allow it to run with aioredis 2.0. 

Referenced the doc at https://aioredis.readthedocs.io/en/latest/api/high-level/#aioredis.client.Redis.zrevrangebyscore, but I don't know if it works as intended.

**Comment by JohnBonJo** [comment]
Thanks [@toyray](https://github.com/toyray)
it worked!
