### ISSUE TITLE
Snare-Stats returns error code 500 Internal Server Error

### ISSUE THREAD

**Issue by tinht21201** [mushorg/tanner#428]
I have successfully connected Snare and Tanner, but when I access Snare-Stats and Session of the UUID web clone, an error code of "500 Internal Server Error" is returned. Please help me.

Best Regards,

**Comment by mzfr** [comment]
@tinht21201 Can you please share logs for both tanner and snare? They should be in `/opt/tanner/tanner.log`, `/opt/tanner/tanner.err` and similarly for snare (just change the file names)

**Comment by tinht21201** [comment]
@mzfr  

This is log of snare:
![Screenshot 2023-07-16 230018](https://github.com/mushorg/tanner/assets/81244900/9b386fe9-f77f-4ea2-9be7-e8fb3c750eb7)

I didn't find any files /opt/tanner/tanner.log, /opt/tanner/tanner.err in tanner
![Screenshot 2023-07-16 230040](https://github.com/mushorg/tanner/assets/81244900/8f1a6579-0186-496d-b861-88e9b3384f9f)
