### ISSUE TITLE
I have 500 Internal Server Error

### ISSUE THREAD

**Issue by namhikelo** [mushorg/tanner#429]
![image](https://github.com/mushorg/tanner/assets/61881881/0d1fd6c4-382f-4d6e-814e-6be66a0beca0)

Error handling request
tanner_web      | Traceback (most recent call last):
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
tanner_web      |     resp = await request_handler(request)
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
tanner_web      |     resp = await handler(request)
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/aiohttp_jinja2/__init__.py", line 91, in wrapped
tanner_web      |     context = await coro(*args)
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/Tanner-0.6.0-py3.9.egg/tanner/web/server.py", line 39, in handle_snare_stats
tanner_web      |     snare_stats = await self.api.return_snare_stats(snare_uuid)
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/Tanner-0.6.0-py3.9.egg/tanner/api/api.py", line 26, in return_snare_stats
tanner_web      |     sessions = await self.return_snare_info(snare_uuid)
tanner_web      |   File "/opt/tanner/tanner-env/lib/python3.9/site-packages/Tanner-0.6.0-py3.9.egg/tanner/api/api.py", line 42, in return_snare_info
tanner_web      |     query_res = await self.redis_client.zrevrangebyscore(uuid, offset=0, count=count)
tanner_web      | TypeError: zrevrangebyscore() got an unexpected keyword argument 'offset'

Please help me.

Best Regards,

**Comment by riyanda-s** [comment]
so how did you solve this problem?
