### ISSUE TITLE
Please, remove "<3.0.0" from jinja paquet inside "requirements.txt" file

### ISSUE THREAD

**Issue by q2dg** [mushorg/tanner#432]
It gives a depencendy problem with aiohttp which is solved not specifying any version for jinja package.
Thanks!

**Comment by q2dg** [comment]
Just put "jinja2" where there is "jinja2<3.0.0" in requirements.txt file

**Comment by saadali05** [comment]
> Just put "jinja2" where there is "jinja2<3.0.0" in requirements.txt file

Oky..

**Comment by Adi-gitX** [comment]
hello i want to solve this issue, i am sending a pill request please check and review
