### ISSUE TITLE
The port is required to be int when running snare & tanner

### ISSUE THREAD

**Issue by ismilech** [mushorg/tanner#434]
Hi,

I've already install & run the snare & tanner, but i having with this issue

sudo snare --debug true --auto-update false --host-ip 0.0.0.0 --port 80 --page-dir /opt/snare/pages/example.com --tanner 0.0.0.0
/usr/local/bin/snare:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('Snare==0.3.0', 'snare')

   _____ _   _____    ____  ______
  / ___// | / /   |  / __ \/ ____/
  \__ \/  |/ / /| | / /_/ / __/
 ___/ / /|  / ___ |/ _, _/ /___
/____/_/ |_/_/  |_/_/ |_/_____/

serving with uuid b4b5f81c-4be9-4492-bdca-426f538b6680
Debug logs will be stored in /opt/snare/snare.log
Error logs will be stored in /opt/snare/snare.err
**The port is required to be int.**

**Comment by afeena** [comment]
please see https://github.com/mushorg/snare/issues/330
