### ISSUE TITLE
Tanner "Detection Type" shows only index, unknown and xss

### ISSUE THREAD

**Issue by djoker77** [mushorg/tanner#436]
Hello everyone,
I recently reported an issue on the t-pot page about Tanner not identifying any other attack types than XSS. Maybe you know why this is the case. Snare and Tanner are running normally, but I tried a couple attacks like SQLi, RFI/LFI or XXE, but neither of those were detected. Instead, they were classified as index or unknown. Can you help me with this issue, or do you know the reason for this behavior? (Speculation would also help)

Issue at t-pot:
https://github.com/telekom-security/tpotce/issues/1560

**Comment by afeena** [comment]
please see reply in https://github.com/mushorg/snare/issues/331
