### ISSUE TITLE
RFI emulation 

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#5]
By using [PHPox](https://github.com/mushorg/phpox) as a service we should be able to run injected PHP code and return the results to the adversary in a timely manner. We are primarily interested in executing those PHP scripts that try to evaluate the vulnerability of the web application. Bot's are interesting too but they usually require longer execution time (this could be done separately).

**Comment by glaslos** [comment]
How should SNARE behave if TANNER detects a RFI?

**Comment by glaslos** [comment]
Some background information on RFI: https://en.wikipedia.org/wiki/File_inclusion_vulnerability

**Comment by afeena** [comment]
SNARE should return the result of rfi emulation to the user. 

I think about next structure:
- TANNER detect rfi
- TANNER rfi emulation download file and run PHPox as a service with this file
- PHPox return the result to TANNER(?) 
- TANNER return to SNARE result of execution or error of execution
- User get the result on the page

Is this correct in general or not?

**Comment by glaslos** [comment]
Sounds good! Yes, PHPox replies to TANNER.

**Comment by afeena** [comment]
I start with emulation:
[https://github.com/afeena/tanner/commit/dfa64a16fd7dd40bf10799c57ef356533160e9d3](url)

I will be glad, if you give me some feedback before I continue.

**Comment by glaslos** [comment]
Done with 4c4e991
