### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by afeena** [mushorg/tanner#68]
How should we organize logging system? What info should we write to logs? Should we replace print messages with logs?

**Comment by glaslos** [comment]
We should definitely remove all prints and move it into a logging handler. Go for a simple syslog for now. I am currently finalizing HPFeeds2 (data collection framework for the Honeynet Project) and we will use that to collect the data (simple HTTP RESTful API).

**Comment by glaslos** [comment]
Closed with baadc53
