### ISSUE TITLE
Track sessions

### ISSUE THREAD

**Issue by glaslos** [mushorg/tanner#7]
Add the capability to track client sessions. Be it through the IP address, user agent, cookies... We had [something](https://github.com/mushorg/glastopf/blob/master/glastopf/modules/processing/profiler.py) along those lines in Glastopf.

**Comment by afeena** [comment]
Is this the SNARE task? In TANNER we get only SNARE socket info or we should pass client data to TANNER?
How should we store tracked data? DB?

**Comment by glaslos** [comment]
We should pass IP info from SNARE to TANNER.
Keep the data in memory for the beginning. Consider how to clean up old sessions. Have a look how we did session tracking in Conpot: https://github.com/mushorg/conpot/blob/master/conpot/core/session_manager.py

**Comment by glaslos** [comment]
Closed with 6fa5640
