### ISSUE TITLE
How do I run tanner?

### ISSUE THREAD

**Issue by polancossj** [mushorg/tanner#82]
How do I run tanner?

I need to see the .log file  

Where I find it? 

thanks

**Comment by afeena** [comment]
You can simply run ``python setup.py install`` in tanner directory, and then run TANNER ``sudo tanner``

**Note:** please, run tanner from source ``tanner/tanner`` directory until my last pr is merged.

Logs stored in the source ``tanner/tanner`` directory

**Comment by TusharFale** [comment]
where i get tanner tool software?

**Comment by afeena** [comment]
@TusharFale Could you please describe your problem more clearly?

Section from quick start guide:

Setup and run TANNER

* Get TANNER: git clone https://github.com/mushorg/tanner.git
* Go to the TANNER source directory: cd tanner
* Install requirements: pip3 install -r requirements.txt
* Install TANNER: python3 setup.py install
* Run TANNER: sudo tanner
