### ISSUE TITLE
problem with file vdocs.json

### ISSUE THREAD

**Issue by polancossj** [mushorg/tanner#88]
when i run snare with tanner service i have the follow error:

![](http://image.prntscr.com/image/591d18b5103641bbbdc865399fe210dc.png)

this is a bug? or why happen?

Thanks!

**Comment by afeena** [comment]
It's a bug, #90 should fix it.

**Comment by glaslos** [comment]
reopen if it still happens after merging #90

**Comment by glaslos** [comment]
Just merged #90 please check if that solves your issue.
