### ISSUE TITLE
Future?

### ISSUE THREAD

**Issue by dufferzafar** [mushorg/tanner#9]
I think this project has [not been selected](https://summerofcode.withgoogle.com/organizations/5000784504684544/?sp-page_size=48#projects) as a part of GSoC'16. 

Will you be working on this in your personal time?

If not, then I'd like to ask you the same thing I've asked before, Can I port this (& snare) to flask? :pray: 
I have no technical reason to do this. Just that I'm really well versed with flask (& things like how its projects should be structure etc.) 

I actually want to work on this idea in any free time I can find, as I think there's a lot I could learn. But, the project involves a lot of things that are completely foreign to me, and I don't want the choice of a web framework etc. weighing me down (`asyncio` just feels like one *more* thing I'll have to learn.) I am just trying to move to towards a comfortable territory so I can focus on stuff that actually matters - the honeynet, vulnerabilities etc.

Let me know what you feel.

**Comment by glaslos** [comment]
Actually we got a student (@afeena) working on it :) I will also continue working on it. Especially the data logging part of this project. I will discuss flask with afeena as she is going to work on this primarily. asyncio is something I highly recommend you to learn as it was the main reason for me to switch from Python2.7 to Python3. No more gevent, thread magic :)
I'm definitely looking forward to your contributions. I think it's best if you just pick a topic you are interested in so I can guide you on how to get started. We can schedule a call if that would help you.

**Comment by dufferzafar** [comment]
I'm sorry I wasn't aware of the fact that this is afeena's project.

If she too finds Flask okay for this, then that's great otherwise I'll just go ahead and learn asyncio, I guess.

I am interested in this project because I'm interested in learning about various vulnerabilities. I currently have a very basic idea of how LFI / SQLi work, and I think I could learn more about them by implementing their emulation etc.

I'll have my own GSoC project work too so I'm not even sure of how much time I'll be able to put into this but yeah I'll definitely be reading all the patches that get submitted.
