### ISSUE TITLE
tanner not runnig after complete installation

### ISSUE THREAD

**Issue by hamza005** [mushorg/tanner#96]
i have installed the redis-server and php sanbox according to given instructions and so as tanner. redis server and sandbox is working well. but the tanner is not working ...here is the output after i give command `sudo tanner` in tanner directory. 
![screenshot from 2016-12-10 21-14-43](https://cloud.githubusercontent.com/assets/20417498/21074560/b4956770-bf1d-11e6-8920-6fcb6bfc6329.png)

**Comment by afeena** [comment]
Hi.
As I see, your tanner works well. It is not print anything to console, all logs stored in /opt/tanner/tanner.log
Just visit 127.0.0.1:8090 to see that it works

**Comment by hamza005** [comment]
:) done. But one thing i would like to ask, as i'm a new user to cyber threats and intelligence, i would like to ask that how i can link snare with tanner to handle all the traffic and for making response to the traffic?

**Comment by afeena** [comment]
Great! :)

Just run SNARE with ``--tanner`` parameter (put ip or domain name)

**Comment by hamza005** [comment]
Without Tanner, SNARE is working well and following is the screen shot of the website while SNARE is running.
![screenshot from 2016-12-14 18-24-02](https://cloud.githubusercontent.com/assets/20417498/21183677/d1ec0e2c-c22a-11e6-99d1-963f2da94305.png)

Now when i used Tanner with SNARE, i used the following command line as per your instruction but SNARE seemed to be not working well. 
![screenshot from 2016-12-14 18-22-05](https://cloud.githubusercontent.com/assets/20417498/21183724/0cbf29e4-c22b-11e6-8b61-47c04439da8d.png)

After that when i gave URL of my website in the browser, there were a problem loading the page. The screen shot of the browser is:
![screenshot from 2016-12-14 18-24-25](https://cloud.githubusercontent.com/assets/20417498/21183766/4357c510-c22b-11e6-8e35-a003240250ef.png)

Can You please me find what's going on?

**Comment by afeena** [comment]
You should put in tanner parameter ip or domain name of your running TANNER host, not the site, which you cloned :)

**Comment by glaslos** [comment]
You can run snare and tanner on the same host if you make sure they run on different ports.

**Comment by hamza005** [comment]
Thanks a lot :) It's working now. After giving the login credentials, the browser reload the same login page with plain HTML script. Here is the screen shot. 
![screenshot from 2016-12-14 19-05-18](https://cloud.githubusercontent.com/assets/20417498/21184967/965b0998-c230-11e6-9d65-4fada93e2422.png)

Is it the expected behavior?

**Comment by glaslos** [comment]
Can you check the server headers? Especially content-type

**Comment by afeena** [comment]
I know this problem. SNARE can't understand mime-type (based on filename). I hope we can fix it soon

**Comment by glaslos** [comment]
Closing this issue now. @afeena can you create a new issue for the mime type?

**Comment by afeena** [comment]
@glaslos Sure

**Comment by hamza005** [comment]
Thank You. Hope you will fix the problems soon :)
